# Generated by Django 5.1.6 on 2025-02-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_discount_stripe_coupon_id_tax_stripe_tax_rate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taxes',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
